version: "3.9"

services:
  db:
    image: postgres:14
    container_name: erp_nectux_db
    restart: always
    environment:
      POSTGRES_DB: erp_nectux
      POSTGRES_USER: axelor
      POSTGRES_PASSWORD: axelor
    volumes:
      - pgdata_Orgs:/var/lib/postgresql/data
    ports:
      - "5465:5432"

  app:
    build: .
    container_name: erp_nectux_app
    restart: always
    depends_on:
      - db
    ports:
      - "8010:8080"

volumes:
  pgdata_Orgs:
